version: '2.2'
services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - elastic


  kib01:
    image: docker.elastic.co/kibana/kibana:6.8.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

  web:
    build: .
    depends_on:
      es01:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge